import { useState } from 'react';

const ReadmePreview = ({ content, onEdit, onSave }) => {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
            <div className="bg-gray-800 px-4 py-2 flex justify-between items-center">
                <h3 className="text-white font-medium">README.md Preview</h3>
                <div className="flex space-x-2">
                    <button
                        onClick={onEdit}
                        className="text-gray-300 hover:text-white text-sm px-3 py-1 rounded hover:bg-gray-700"
                    >
                        Edit Information
                    </button>
                    <button
                        onClick={handleCopy}
                        className="bg-indigo-600 hover:bg-indigo-700 text-white text-sm px-3 py-1 rounded transition-colors"
                    >
                        {copied ? 'Copied!' : 'Copy Markdown'}
                    </button>
                    {onSave && (
                        <button
                            onClick={onSave}
                            className="bg-green-600 hover:bg-green-700 text-white text-sm px-3 py-1 rounded transition-colors"
                        >
                            Save Project
                        </button>
                    )}
                </div>
            </div>

            <div className="p-0">
                <textarea
                    readOnly
                    value={content}
                    className="w-full h-[60vh] p-4 font-mono text-sm bg-gray-50 text-gray-800 resize-none focus:outline-none"
                />
            </div>

            <div className="bg-gray-100 px-4 py-3 text-sm text-gray-500 border-t flex justify-between">
                <span>{content.length} characters</span>
                <span>Generated by AI README Generator</span>
            </div>
        </div>
    );
};

export default ReadmePreview;
