// import { useState } from 'react';
// import { pushReadme } from '../../api/githubApi';

// const ReadmePreview = ({ content, onEdit, onSave, entity }) => {
//     const [copied, setCopied] = useState(false);
//     const [pushing, setPushing] = useState(false);
//     const [pushResult, setPushResult] = useState(null);
//     const [pushError, setPushError] = useState(null);

//     const handleCopy = () => {
//         navigator.clipboard.writeText(content);
//         setCopied(true);
//         setTimeout(() => setCopied(false), 2000);
//     };

//     const handlePush = async () => {
//         setPushError(null);
//         setPushResult(null);

//         // ✅ Ensure project is saved
//         if (!entity?._id) {
//             setPushError('Please save the project before pushing to GitHub.');
//             return;
//         }

//         try {
//             setPushing(true);

//             // ✅ Send only mainEntityId
//             const res = await pushReadme(entity._id);

//             setPushResult(
//                 res.html_url || res.message || 'Pushed successfully'
//             );

//         } catch (err) {
//             console.error(err);
//             setPushError(
//                 err.response?.data?.message ||
//                 err.message ||
//                 'Failed to push README'
//             );
//         } finally {
//             setPushing(false);
//             setTimeout(() => setPushResult(null), 10000);
//         }
//     };

//     return (
//         <div className="bg-white rounded-lg shadow-lg overflow-hidden">

//             {/* Header */}
//             <div className="bg-gray-800 px-4 py-2 flex justify-between items-center">
//                 <h3 className="text-white font-medium">README.md Preview</h3>

//                 <div className="flex space-x-2">
//                     <button
//                         onClick={onEdit}
//                         className="text-gray-300 hover:text-white text-sm px-3 py-1 rounded hover:bg-gray-700"
//                     >
//                         Edit Information
//                     </button>

//                     <button
//                         onClick={handlePush}
//                         disabled={pushing}
//                         className="bg-blue-600 hover:bg-blue-700 text-white text-sm px-3 py-1 rounded transition-colors disabled:opacity-60"
//                     >
//                         {pushing ? 'Pushing...' : 'Push to GitHub'}
//                     </button>

//                     <button
//                         onClick={handleCopy}
//                         className="bg-indigo-600 hover:bg-indigo-700 text-white text-sm px-3 py-1 rounded transition-colors"
//                     >
//                         {copied ? 'Copied!' : 'Copy Markdown'}
//                     </button>

//                     {onSave && (
//                         <button
//                             onClick={onSave}
//                             className="bg-green-600 hover:bg-green-700 text-white text-sm px-3 py-1 rounded transition-colors"
//                         >
//                             Save Project
//                         </button>
//                     )}
//                 </div>
//             </div>

//             {/* Content */}
//             <div className="p-0">
//                 <textarea
//                     readOnly
//                     value={content}
//                     className="w-full h-[60vh] p-4 font-mono text-sm bg-gray-50 text-gray-800 resize-none focus:outline-none"
//                 />
//             </div>

//             {/* Footer */}
//             <div className="bg-gray-100 px-4 py-3 text-sm text-gray-500 border-t flex justify-between">
//                 <span>{content.length} characters</span>
//                 <span>Generated by AI README Generator</span>
//             </div>

//             {/* Success Message */}
//             {pushResult && (
//                 <div className="mt-2 text-sm px-3 py-2 text-green-700 bg-green-50 rounded">
//                     Successfully pushed. View:{' '}
//                     <a
//                         className="underline"
//                         href={pushResult}
//                         target="_blank"
//                         rel="noreferrer"
//                     >
//                         {pushResult}
//                     </a>
//                 </div>
//             )}

//             {/* Error Message */}
//             {pushError && (
//                 <div className="mt-2 text-sm px-3 py-2 text-red-700 bg-red-50 rounded">
//                     {pushError}
//                 </div>
//             )}
//         </div>
//     );
// };

// export default ReadmePreview;


import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { pushReadme } from '../../api/githubApi';

const ReadmePreview = ({ content, onEdit, onSave, entity }) => {
    const { user } = useAuth();
    const navigate = useNavigate();

    const isProUser = user?.isPro === true;

    const [copied, setCopied] = useState(false);
    const [pushing, setPushing] = useState(false);
    const [message, setMessage] = useState(null); // success or error
    const [messageType, setMessageType] = useState(null); // 'success' | 'error'

    const showMessage = (text, type = 'success') => {
        setMessage(text);
        setMessageType(type);

        setTimeout(() => {
            setMessage(null);
            setMessageType(null);
        }, 4000);
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handlePush = async () => {
        if (!isProUser) {
            navigate('/upgrade');
            return;
        }

        if (!entity?._id) {
            showMessage('Please save the project before pushing.', 'error');
            return;
        }

        try {
            setPushing(true);

            await pushReadme(entity._id);

            showMessage('README successfully pushed to GitHub!', 'success');

        } catch (err) {
            showMessage(
                err.response?.data?.message || 'Failed to push README',
                'error'
            );
        } finally {
            setPushing(false);
        }
    };

    return (
        <div className="bg-white rounded-lg shadow-lg overflow-hidden relative">

            {/* HEADER */}
            <div className="bg-gray-800 px-4 py-2 flex justify-between items-center">
                <h3 className="text-white font-medium">README.md Preview</h3>

                <div className="flex space-x-2">

                    <button
                        onClick={onEdit}
                        className="text-gray-300 hover:text-white text-sm px-3 py-1 rounded hover:bg-gray-700"
                    >
                        Edit
                    </button>

                    {isProUser ? (
                        <button
                            onClick={handlePush}
                            disabled={pushing}
                            className="bg-blue-600 hover:bg-blue-700 text-white text-sm px-3 py-1 rounded transition disabled:opacity-60"
                        >
                            {pushing ? 'Pushing...' : 'Push to GitHub'}
                        </button>
                    ) : (
                        <button
                            onClick={() => navigate('/upgrade')}
                            className="bg-amber-500 hover:bg-amber-600 text-white text-sm px-3 py-1 rounded transition"
                        >
                            🔒 Upgrade to Push
                        </button>
                    )}

                    <button
                        onClick={handleCopy}
                        className="bg-indigo-600 hover:bg-indigo-700 text-white text-sm px-3 py-1 rounded transition"
                    >
                        {copied ? 'Copied!' : 'Copy'}
                    </button>

                    {onSave && (
                        <button
                            onClick={onSave}
                            className="bg-green-600 hover:bg-green-700 text-white text-sm px-3 py-1 rounded transition"
                        >
                            Save
                        </button>
                    )}
                </div>
            </div>

            {/* CONTENT */}
            <textarea
                readOnly
                value={content}
                className="w-full h-[60vh] p-4 font-mono text-sm bg-gray-50 text-gray-800 resize-none focus:outline-none"
            />

            {/* FOOTER */}
            <div className="bg-gray-100 px-4 py-3 text-sm text-gray-500 border-t flex justify-between">
                <span>{content.length} characters</span>
                <span>Generated by AI README Generator</span>
            </div>

            {/* MESSAGE (SUCCESS / ERROR) */}
            {message && (
                <div
                    className={`fixed top-6 right-6 z-50 px-4 py-3 rounded-lg shadow-lg text-sm font-medium
                    ${messageType === 'success'
                        ? 'bg-green-600 text-white'
                        : 'bg-red-600 text-white'
                    }`}
                >
                    {message}
                </div>
            )}
        </div>
    );
};

export default ReadmePreview;